structure(list(url = "sleeper/v1/user/solarpool", status_code = 200L, 
    headers = structure(list(date = "Sat, 12 Jun 2021 13:20:14 GMT", 
        `content-type` = "application/json; charset=utf-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", vary = "Accept-Encoding", 
        `cache-control` = "max-age=0, private, must-revalidate", 
        `x-request-id` = "8433f6e3037cbb31eebaa34972928a24", 
        `access-control-allow-origin` = "*", `access-control-expose-headers` = "etag", 
        `access-control-allow-credentials` = "true", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
        `content-encoding` = "gzip", `cf-cache-status` = "MISS", 
        `cf-request-id` = "0aa1fa65dc000005de261f7000000001", 
        `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
        server = "cloudflare", `cf-ray` = "65e3601c9ec705de-IAD"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sat, 12 Jun 2021 13:20:14 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            vary = "Accept-Encoding", `cache-control` = "max-age=0, private, must-revalidate", 
            `x-request-id` = "8433f6e3037cbb31eebaa34972928a24", 
            `access-control-allow-origin` = "*", `access-control-expose-headers` = "etag", 
            `access-control-allow-credentials` = "true", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
            `content-encoding` = "gzip", `cf-cache-status` = "MISS", 
            `cf-request-id` = "0aa1fa65dc000005de261f7000000001", 
            `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
            server = "cloudflare", `cf-ray` = "65e3601c9ec705de-IAD"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"verification\":null,\"username\":\"solarpool\",\"user_id\":\"202892038360801280\",\"token\":null,\"summoner_region\":null,\"summoner_name\":null,\"solicitable\":null,\"real_name\":null,\"phone\":null,\"pending\":null,\"notifications\":null,\"is_bot\":false,\"email\":null,\"display_name\":\"solarpool\",\"deleted\":null,\"data_updated\":null,\"currencies\":null,\"created\":null,\"cookies\":null,\"avatar\":\"a71f864896ba28cbfaa4dc5df5b564e0\"}"), 
    date = structure(1623504014, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.8e-05, 
    connect = 2.9e-05, pretransfer = 7.2e-05, starttransfer = 0.13408, 
    total = 0.134186)), class = "response")
