structure(list(url = "mfl/2020/export?TYPE=myleagues&FRANCHISE_NAMES=1&YEAR=2020&JSON=1", 
    status_code = 200L, headers = structure(list(date = "Sat, 12 Jun 2021 14:01:12 GMT", 
        server = "Apache/2.4.18 (Unix) mod_apreq2-20090110/2.8.0 mod_perl/2.0.9 Perl/v5.10.1", 
        `content-type` = "application/json; charset=utf-8", expires = "Fri, 12 Jun 2020 14:01:12 GMT", 
        `cache-control` = "private", `access-control-allow-origin` = "https://www70.myfantasyleague.com", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "162", `set-cookie` = "utf-8", targethost = "www70"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sat, 12 Jun 2021 14:01:12 GMT", 
            server = "Apache/2.4.18 (Unix) mod_apreq2-20090110/2.8.0 mod_perl/2.0.9 Perl/v5.10.1", 
            `content-type` = "application/json; charset=utf-8", 
            expires = "Fri, 12 Jun 2020 14:01:12 GMT", `cache-control` = "private", 
            `access-control-allow-origin` = "https://www70.myfantasyleague.com", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "162", `set-cookie` = "utf-8", 
            targethost = "www70"), class = c("insensitive", "list"
        )))), cookies = structure(list(domain = c(".myfantasyleague.com", 
    ".myfantasyleague.com"), flag = c(TRUE, TRUE), path = c("/", 
    "/"), secure = c(FALSE, FALSE), expiration = structure(c(Inf, 
    1626098472), class = c("POSIXct", "POSIXt")), name = c("MFL_USER_ID", 
    "MFL_PW_SEQ"), value = c("bh1s2MuUvrXmhFT4fBCBI21QQORzzHT%2F%2Bw%3D%3D", 
    "aB9q2MqQseit0gK6")), row.names = c(NA, -2L), class = "data.frame"), 
    content = charToRaw("{\"version\":\"1.0\",\"leagues\":{\"league\":{\"franchise_id\":\"0001\",\"url\":\"https://www70.myfantasyleague.com/2020/home/21499\",\"name\":\"testestest\",\"franchise_name\":\"Franchise 1\",\"league_id\":\"21499\"}},\"encoding\":\"utf-8\"}"), 
    date = structure(1623506472, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.7e-05, 
    connect = 2.8e-05, pretransfer = 8.1e-05, starttransfer = 0.251213, 
    total = 0.251322)), class = "response")
