structure(list(url = "https://www57.myfantasyleague.com/2020/export?TYPE=rules&L=37920&JSON=1", 
    status_code = 200L, headers = structure(list(date = "Sat, 12 Jun 2021 13:59:29 GMT", 
        server = "Apache/2.4.18 (Unix) mod_apreq2-20090110/2.8.0 mod_perl/2.0.9 Perl/v5.10.1", 
        `content-type` = "application/json; charset=utf-8", expires = "Fri, 12 Jun 2020 13:59:29 GMT", 
        `cache-control` = "private", `access-control-allow-origin` = "https://www57.myfantasyleague.com", 
        vary = "Accept-Encoding", `content-encoding` = "gzip", 
        `content-length` = "261", `set-cookie` = "utf-8"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 302L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sat, 12 Jun 2021 13:59:29 GMT", 
            server = "Apache/2.4.18 (Unix) mod_apreq2-20090110/2.8.0 mod_perl/2.0.9 Perl/v5.10.1", 
            location = "https://www57.myfantasyleague.com/2020/export?TYPE=rules&L=37920&JSON=1", 
            `content-length` = "0", targethost = "www71"), class = c("insensitive", 
        "list"))), list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sat, 12 Jun 2021 13:59:29 GMT", 
            server = "Apache/2.4.18 (Unix) mod_apreq2-20090110/2.8.0 mod_perl/2.0.9 Perl/v5.10.1", 
            `content-type` = "application/json; charset=utf-8", 
            expires = "Fri, 12 Jun 2020 13:59:29 GMT", `cache-control` = "private", 
            `access-control-allow-origin` = "https://www57.myfantasyleague.com", 
            vary = "Accept-Encoding", `content-encoding` = "gzip", 
            `content-length` = "261", `set-cookie` = "utf-8"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = c(".myfantasyleague.com", 
    ".myfantasyleague.com"), flag = c(TRUE, TRUE), path = c("/", 
    "/"), secure = c(FALSE, FALSE), expiration = structure(c(Inf, 
    1626098324), class = c("POSIXct", "POSIXt")), name = c("MFL_USER_ID", 
    "MFL_PW_SEQ"), value = c("bh1s2MuUvrXmhFT4fBCBI21QQORzzHT%2F%2Bw%3D%3D", 
    "aB9q2MqQseit3Qe%2F")), row.names = c(NA, -2L), class = "data.frame"), 
    content = charToRaw("{\"version\":\"1.0\",\"rules\":{\"positionRules\":[{\"positions\":\"TE\",\"rule\":{\"points\":{\"$t\":\"*1.5\"},\"range\":{\"$t\":\"0-99\"},\"event\":{\"$t\":\"CC\"}}},{\"positions\":\"WR\",\"rule\":{\"points\":{\"$t\":\"*0.5\"},\"range\":{\"$t\":\"0-99\"},\"event\":{\"$t\":\"CC\"}}},{\"positions\":\"QB|RB|WR|TE|PK\",\"rule\":[{\"points\":{\"$t\":\"*4\"},\"range\":{\"$t\":\"1-10\"},\"event\":{\"$t\":\"#P\"}},{\"points\":{\"$t\":\"*0.04\"},\"range\":{\"$t\":\"1-999\"},\"event\":{\"$t\":\"PY\"}},{\"points\":{\"$t\":\"*-2\"},\"range\":{\"$t\":\"1-10\"},\"event\":{\"$t\":\"IN\"}},{\"points\":{\"$t\":\"*1\"},\"range\":{\"$t\":\"1-10\"},\"event\":{\"$t\":\"P2\"}},{\"points\":{\"$t\":\"*6\"},\"range\":{\"$t\":\"1-10\"},\"event\":{\"$t\":\"#R\"}},{\"points\":{\"$t\":\"*0.1\"},\"range\":{\"$t\":\"1-999\"},\"event\":{\"$t\":\"RY\"}},{\"points\":{\"$t\":\"*2\"},\"range\":{\"$t\":\"1-10\"},\"event\":{\"$t\":\"R2\"}},{\"points\":{\"$t\":\"*6\"},\"range\":{\"$t\":\"1-10\"},\"event\":{\"$t\":\"#C\"}},{\"points\":{\"$t\":\"*0.1\"},\"range\":{\"$t\":\"1-999\"},\"event\":{\"$t\":\"CY\"}},{\"points\":{\"$t\":\"*2\"},\"range\":{\"$t\":\"1-10\"},\"event\":{\"$t\":\"C2\"}},{\"points\":{\"$t\":\"*-1\"},\"range\":{\"$t\":\"0-10\"},\"event\":{\"$t\":\"FU\"}},{\"points\":{\"$t\":\"*-1\"},\"range\":{\"$t\":\"0-10\"},\"event\":{\"$t\":\"FL\"}},{\"points\":{\"$t\":\"1/1\"},\"range\":{\"$t\":\"1-50\"},\"event\":{\"$t\":\"1R\"}},{\"points\":{\"$t\":\"1/1\"},\"range\":{\"$t\":\"1-50\"},\"event\":{\"$t\":\"1C\"}}]}]},\"encoding\":\"utf-8\"}"), 
    date = structure(1623506369, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0.138632, namelookup = 5.1e-05, 
    connect = 5.2e-05, pretransfer = 0.000144, starttransfer = 0.329722, 
    total = 0.329844)), class = "response")
