structure(list(url = "sleeper/v1/league/521379020332068864/traded_picks", 
    status_code = 200L, headers = structure(list(date = "Sat, 12 Jun 2021 13:18:35 GMT", 
        `content-type` = "application/json; charset=utf-8", `transfer-encoding` = "chunked", 
        connection = "keep-alive", vary = "Accept-Encoding", 
        `cache-control` = "max-age=0, private, must-revalidate", 
        `x-request-id` = "95d1e2f022a596058bad4dce5d27afed", 
        `access-control-allow-origin` = "*", `access-control-expose-headers` = "etag", 
        `access-control-allow-credentials` = "true", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
        `content-encoding` = "gzip", `cf-cache-status` = "MISS", 
        `cf-request-id` = "0aa1f8e00d000059ce3197c000000001", 
        `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
        server = "cloudflare", `cf-ray` = "65e35dace87d59ce-IAD"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sat, 12 Jun 2021 13:18:35 GMT", 
            `content-type` = "application/json; charset=utf-8", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            vary = "Accept-Encoding", `cache-control` = "max-age=0, private, must-revalidate", 
            `x-request-id` = "95d1e2f022a596058bad4dce5d27afed", 
            `access-control-allow-origin` = "*", `access-control-expose-headers` = "etag", 
            `access-control-allow-credentials` = "true", `strict-transport-security` = "max-age=15724800; includeSubDomains", 
            `content-encoding` = "gzip", `cf-cache-status` = "MISS", 
            `cf-request-id` = "0aa1f8e00d000059ce3197c000000001", 
            `expect-ct` = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", 
            server = "cloudflare", `cf-ray` = "65e35dace87d59ce-IAD"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("[{\"season\":\"2020\",\"round\":1,\"roster_id\":1,\"previous_owner_id\":4,\"owner_id\":8},{\"season\":\"2020\",\"round\":2,\"roster_id\":1,\"previous_owner_id\":1,\"owner_id\":4},{\"season\":\"2020\",\"round\":3,\"roster_id\":1,\"previous_owner_id\":1,\"owner_id\":4},{\"season\":\"2020\",\"round\":4,\"roster_id\":1,\"previous_owner_id\":1,\"owner_id\":8},{\"season\":\"2021\",\"round\":1,\"roster_id\":1,\"previous_owner_id\":1,\"owner_id\":2},{\"season\":\"2020\",\"round\":1,\"roster_id\":2,\"previous_owner_id\":2,\"owner_id\":11},{\"season\":\"2020\",\"round\":2,\"roster_id\":2,\"previous_owner_id\":2,\"owner_id\":9},{\"season\":\"2020\",\"round\":3,\"roster_id\":2,\"previous_owner_id\":5,\"owner_id\":12},{\"season\":\"2020\",\"round\":4,\"roster_id\":2,\"previous_owner_id\":2,\"owner_id\":11},{\"season\":\"2021\",\"round\":1,\"roster_id\":2,\"previous_owner_id\":2,\"owner_id\":5},{\"season\":\"2021\",\"round\":3,\"roster_id\":2,\"previous_owner_id\":2,\"owner_id\":1},{\"season\":\"2022\",\"round\":1,\"roster_id\":2,\"previous_owner_id\":2,\"owner_id\":5},{\"season\":\"2022\",\"round\":3,\"roster_id\":2,\"previous_owner_id\":2,\"owner_id\":7},{\"season\":\"2020\",\"round\":1,\"roster_id\":3,\"previous_owner_id\":3,\"owner_id\":7},{\"season\":\"2020\",\"round\":4,\"roster_id\":4,\"previous_owner_id\":4,\"owner_id\":1},{\"season\":\"2021\",\"round\":2,\"roster_id\":4,\"previous_owner_id\":4,\"owner_id\":1},{\"season\":\"2021\",\"round\":3,\"roster_id\":4,\"previous_owner_id\":4,\"owner_id\":1},{\"season\":\"2021\",\"round\":4,\"roster_id\":4,\"previous_owner_id\":4,\"owner_id\":1},{\"season\":\"2020\",\"round\":1,\"roster_id\":5,\"previous_owner_id\":5,\"owner_id\":7},{\"season\":\"2020\",\"round\":2,\"roster_id\":5,\"previous_owner_id\":5,\"owner_id\":12},{\"season\":\"2020\",\"round\":3,\"roster_id\":5,\"previous_owner_id\":12,\"owner_id\":4},{\"season\":\"2020\",\"round\":4,\"roster_id\":5,\"previous_owner_id\":5,\"owner_id\":2},{\"season\":\"2021\",\"round\":3,\"roster_id\":5,\"previous_owner_id\":7,\"owner_id\":1},{\"season\":\"2020\",\"round\":1,\"roster_id\":6,\"previous_owner_id\":7,\"owner_id\":5},{\"season\":\"2021\",\"round\":2,\"roster_id\":6,\"previous_owner_id\":6,\"owner_id\":4},{\"season\":\"2020\",\"round\":1,\"roster_id\":7,\"previous_owner_id\":5,\"owner_id\":2},{\"season\":\"2020\",\"round\":2,\"roster_id\":7,\"previous_owner_id\":7,\"owner_id\":5},{\"season\":\"2021\",\"round\":1,\"roster_id\":7,\"previous_owner_id\":7,\"owner_id\":8},{\"season\":\"2021\",\"round\":4,\"roster_id\":7,\"previous_owner_id\":7,\"owner_id\":8},{\"season\":\"2022\",\"round\":1,\"roster_id\":7,\"previous_owner_id\":7,\"owner_id\":2},{\"season\":\"2020\",\"round\":2,\"roster_id\":8,\"previous_owner_id\":8,\"owner_id\":7},{\"season\":\"2020\",\"round\":3,\"roster_id\":8,\"previous_owner_id\":4,\"owner_id\":12},{\"season\":\"2020\",\"round\":4,\"roster_id\":8,\"previous_owner_id\":4,\"owner_id\":12},{\"season\":\"2021\",\"round\":1,\"roster_id\":8,\"previous_owner_id\":8,\"owner_id\":4},{\"season\":\"2021\",\"round\":2,\"roster_id\":8,\"previous_owner_id\":8,\"owner_id\":4},{\"season\":\"2021\",\"round\":3,\"roster_id\":8,\"previous_owner_id\":8,\"owner_id\":11},{\"season\":\"2021\",\"round\":4,\"roster_id\":8,\"previous_owner_id\":8,\"owner_id\":1},{\"season\":\"2020\",\"round\":3,\"roster_id\":11,\"previous_owner_id\":11,\"owner_id\":2},{\"season\":\"2020\",\"round\":2,\"roster_id\":12,\"previous_owner_id\":12,\"owner_id\":5},{\"season\":\"2020\",\"round\":3,\"roster_id\":12,\"previous_owner_id\":12,\"owner_id\":5},{\"season\":\"2021\",\"round\":2,\"roster_id\":12,\"previous_owner_id\":12,\"owner_id\":5}]"), 
    date = structure(1623503915, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.5e-05, 
    connect = 3.7e-05, pretransfer = 0.000116, starttransfer = 0.136906, 
    total = 0.137312)), class = "response")
